name: Brevly CI/CD

on:
  push:
    branches:
      - main
      - master
    paths:
      - web/**
      - server/**
      - .github/workflows/main.yml

jobs:
  detect_changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      web_changed: ${{ steps.filter.outputs.web }}
      server_changed: ${{ steps.filter.outputs.server }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Filter Changed Paths
        id: filter
        uses: dorny/paths-filter@v3.0.2
        with:
          filters: |
            web:
              - web/**
            server:
              - server/**

  build_backend:
    name: Build & Deploy Backend
    needs: detect_changes
    if: ${{ needs.detect_changes.outputs.server_changed == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        id: configure_aws_credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to AWS ECR
        id: login_ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate Tag
        id: generate_tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Build Image for Trivy Scan
        uses: docker/build-push-action@v6
        with:
          context: ./server
          file: ./server/Dockerfile
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: brevly:scan-test

      - name: Run Trivy Scan
        id: run_trivy_scan
        uses: aquasecurity/trivy-action@0.29.0
        with:
          image-ref: brevly:scan-test
          format: table
          ignore-unfixed: true
          vuln-type: os,library
          severity: CRITICAL,HIGH

      - name: Build & Push Image to AWS ECR
        uses: docker/build-push-action@v6
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          cache-from: type=gha
          tags: |
            ${{ steps.login_ecr.outputs.registry }}/${{ vars.ECR_REPOSITORY }}:${{ steps.generate_tag.outputs.sha }}

      - name: Build & Push Image to DockerHub
        uses: docker/build-push-action@v6
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          cache-from: type=gha
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/brevly:${{ steps.generate_tag.outputs.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/brevly:latest

      - name: Trigger Deploy on Render
        if: github.ref == 'refs/heads/main'
        env:
          DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl -X POST "$DEPLOY_HOOK_URL"
